spring:
  profiles:
    active: local-dev

---
spring.profiles: local-dev
spring:
  profiles:
    include: local-postgresql-credentials,debug
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${TODOLIST_DB_HOST:localhost}:5432/todolist-db
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: local-postgresql-credentials
  datasource:
    username: postgres
    password: password

---
spring:
  profiles: debug
logging:
  level:
    com.alevel.java.nix.todolist: debug
