version: '3'
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist-db
    volumes:
      - database-data:/home/pixel/db/
    ports:
      - 5432:5432

  todolist:
    image: todolist:0.0.1-SNAPSHOT
    environment:
      TODOLIST_DB_HOST: database
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  database-data:
    driver: local
